services:
  postgres:
    image: postgres:17-alpine
    container_name: him-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_inventory
    volumes:
      - him-pgdata:/var/lib/postgresql/data

volumes:
  him-pgdata:
